---
ports:
  - port: 3000
    onOpen: open-preview
    # The port is visible to allow sharing of the preview
    visibility: public

tasks:
  - name: "Vite"
    before: |
      brew install git-lfs
      git lfs install
      git lfs pull
    init: yarn install
    command: |
      export HMR_HOST=`gp url 3000`
      yarn run dev

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

vscode:
  extensions:
    - svelte.svelte-vscode
    - fivethree.vscode-svelte-snippets
    - editorconfig.editorconfig
    - davidanson.vscode-markdownlint
    - bpruitt-goddard.mermaid-markdown-syntax-highlighting
    - esbenp.prettier-vscode
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
    - voorjaar.windicss-intellisense
